name: env
channels:
  - conda-forge
  - defaults
dependencies: 
  - A
  - B
  - BeaEnginePython
  - ConfigParser
  - Cython
  - HTMLParser
  - IPython
  - OpenGL
  - OpenSSL
  - PIL
  - PyQt4
  - PyQt5
  - PyQt6
  - PySide
  - PySide2
  - PySide6
  - Pyside
  - Queue
  - StringIO
  - System
  - Tkinter
  - __about__
  - __builtin__
  - __future__
  - __main__
  - __pypy__
  - __version__
  - _abc
  - _abcoll
  - _adapters
  - _aix_support
  - _api
  - _apply_pyprojecttoml
  - _ast
  - _async
  - _asyncio
  - _bisect
  - _blake2
  - _bootstrap
  - _bootstrap_external
  - _bz2
  - _casefix
  - _cell_widths
  - _cffi
  - _cmp
  - _cmsgpack
  - _codecs
  - _codecs_cn
  - _codecs_hk
  - _codecs_iso2022
  - _codecs_jp
  - _codecs_kr
  - _codecs_tw
  - _collections
  - _collections_abc
  - _common
  - _compat
  - _compat_pickle
  - _compression
  - _config
  - _constants
  - _contextvars
  - _crypt
  - _csv
  - _ctypes
  - _ctypes_test
  - _curses
  - _curses_panel
  - _datetime
  - _dbm
  - _decimal
  - _dist_ver
  - _dists
  - _distutils
  - _distutils_hack
  - _elementtree
  - _elffile
  - _emoji_codes
  - _emoji_replace
  - _envs
  - _eventloop_macos
  - _exceptions
  - _export_format
  - _extension
  - _factories
  - _fileno
  - _frozen_importlib
  - _frozen_importlib_external
  - _funcs
  - _functools
  - _gdbm
  - _hashlib
  - _heapq
  - _helpers
  - _imp
  - _impl
  - _importlib
  - _imports
  - _in_process
  - _internal_utils
  - _io
  - _itertools
  - _json
  - _legacy
  - _locale
  - _log
  - _log_render
  - _loop
  - _lsprof
  - _lzma
  - _macos
  - _macos_compat
  - _make
  - _manylinux
  - _markupbase
  - _md5
  - _meta
  - _modified
  - _monitor
  - _msvccompiler
  - _multibytecodec
  - _multiprocessing
  - _next_gen
  - _opcode
  - _openssl
  - _operator
  - _osx_support
  - _overlapped
  - _palettes
  - _parser
  - _path
  - _pick
  - _pickle
  - _poll
  - _position_node_finder
  - _posixshmem
  - _posixsubprocess
  - _process_cli
  - _process_common
  - _process_emscripten
  - _process_posix
  - _process_win32
  - _pslinux
  - _pssunos
  - _psutil_windows
  - _pswindows
  - _py_abc
  - _pydatetime
  - _pydecimal
  - _pydev_bundle
  - _pydev_runfiles
  - _pydevd_bundle
  - _pydevd_bundle_ext
  - _pydevd_frame_eval
  - _pydevd_frame_eval_ext
  - _pypy_wait
  - _pytest
  - _queue
  - _random
  - _ratio
  - _re
  - _reqs
  - _scproxy
  - _securetransport
  - _sha1
  - _sha2
  - _sha3
  - _signal
  - _sitebuiltins
  - _socket
  - _spinners
  - _sqlite3
  - _sre
  - _ssl
  - _ssl_constants
  - _stat
  - _statistics
  - _string
  - _strptime
  - _struct
  - _structures
  - _subprocess
  - _symtable
  - _testcapi
  - _testinternalcapi
  - _text
  - _thread
  - _threading_local
  - _timer
  - _tkinter
  - _tokenize
  - _tokenizer
  - _tqdm_pandas
  - _tracemalloc
  - _types
  - _typeshed
  - _typing
  - _util
  - _uuid
  - _version
  - _version_info
  - _warnings
  - _weakref
  - _weakrefset
  - _winapi
  - _windows
  - _winreg
  - _wmi
  - _wrap
  - _xxinterpchannels
  - _xxsubinterpreters
  - _zmq
  - _zoneinfo
  - abc
  - actions
  - adapter
  - adapters
  - add_code_to_python_process
  - after
  - aifc
  - align
  - android
  - ansi
  - ansi_escape_sequences
  - ansitowin32
  - anydbm
  - api
  - app
  - application
  - appnope
  - archive_util
  - argcomplete
  - argparse
  - array
  - ast
  - astroid
  - astroid_compat
  - asttokens
  - async_case
  - async_generator
  - async_helpers
  - asynchronous
  - asyncio
  - asyncssh
  - atexit
  - atheris
  - attach_pydevd
  - attach_script
  - attr
  - attrs
  - attrsettr
  - audioop
  - auth
  - auto
  - auto_suggest
  - autocall
  - autonotebook
  - backports
  - base
  - base64
  - base_comm
  - base_events
  - basic
  - bdb
  - bdist_egg
  - bdist_wheel
  - before
  - before_sleep
  - big5freq
  - big5prober
  - binascii
  - bindings
  - bisect
  - black
  - blocking
  - box
  - btm_utils
  - buffer
  - build
  - build_py
  - builtins
  - bz2
  - cPickle
  - cProfile
  - cache
  - calendar
  - candidates
  - capstone
  - capture
  - case
  - ccompiler
  - cells
  - cerealizer
  - certs
  - cffi
  - cgi
  - channels
  - channelsabc
  - chardet
  - chardistribution
  - charsetgroupprober
  - charsetprober
  - chunk
  - cli
  - client
  - clientabc
  - clipboard
  - cloudpickle
  - clr
  - cmath
  - cmd
  - code
  - codec
  - codecs
  - codeop
  - codingstatemachine
  - codingstatemachinedict
  - collections
  - color
  - color_depth
  - color_triplet
  - colorable
  - colorama
  - colorsys
  - columns
  - comm
  - command
  - common
  - compat
  - compileall
  - compiler
  - completer
  - completion
  - concurrencytest
  - concurrent
  - conemu
  - config
  - configparser
  - configurable
  - connect
  - connection
  - connectionpool
  - console
  - consoleapp
  - constants
  - constrain
  - containers
  - context
  - contextlib
  - contextlib2
  - contextvars
  - contrib
  - control
  - controls
  - convert
  - converter
  - converters
  - cookies
  - copy
  - copyreg
  - core
  - coroutines
  - corpus
  - coverage
  - cp949prober
  - crash
  - crypt
  - cryptography
  - csv
  - ctags
  - ctypes
  - curio
  - current
  - curses
  - custom_doctests
  - cython
  - dask
  - data_structures
  - database
  - dataclasses
  - datetime
  - dateutil
  - dbm
  - debug
  - debugger
  - debugpy
  - decimal
  - decoder
  - decorator
  - deduplicate
  - default_styles
  - defaults
  - depends
  - devices
  - diagram
  - dialogs
  - difflib
  - dill
  - dimension
  - dir_util
  - dis
  - disassemble
  - disco
  - discord
  - discovery
  - display
  - display_functions
  - dist
  - dist_info
  - distorm
  - distorm3
  - distro
  - distutils
  - django
  - dl
  - docrepr
  - doctest
  - document
  - docutils
  - domreg
  - draft04
  - draft06
  - draft07
  - dummy
  - dummy_thread
  - dummy_threading
  - egg_info
  - email
  - emoji
  - encoder
  - encoding
  - encodings
  - ensurepip
  - enum
  - enums
  - errno
  - error
  - error_reporting
  - errors
  - escprober
  - escsm
  - eucjpprober
  - euckrfreq
  - euckrprober
  - euctwfreq
  - euctwprober
  - eventloop
  - eventloops
  - events
  - exceptiongroup
  - exceptions
  - executing
  - execution
  - expect
  - ext
  - extension
  - extern
  - extra_validations
  - factory
  - fallback
  - fancy_getopt
  - fastjsonschema
  - fastjsonschema_exceptions
  - fastjsonschema_validations
  - faulthandler
  - fcntl
  - fields
  - file_proxy
  - file_util
  - filecmp
  - filelist
  - filelock
  - filepost
  - filesystem
  - filters
  - fixer_base
  - fixer_util
  - flush_stdout
  - fnmatch
  - forkserver
  - formatted_text
  - formatters
  - formatting
  - forward
  - found_candidates
  - fqdn
  - fractions
  - ftplib
  - functools
  - futures
  - fuzzy_completer
  - gb2312freq
  - gb2312prober
  - gc
  - generator
  - genericpath
  - getipython
  - getopt
  - getpass
  - gettext
  - gevent
  - gi
  - glob
  - glut_support
  - gobject
  - google
  - greenlet
  - greet
  - grp
  - gtk
  - gui
  - gzip
  - handler
  - has_key
  - hashlib
  - headers
  - heap
  - heapq
  - heartbeat
  - hebrewprober
  - helpers
  - highlighter
  - history
  - hmac
  - hooks
  - html
  - htmlentitydefs
  - http
  - httplib
  - hypothesis
  - idlelib
  - idna
  - imp
  - import_helper
  - importlib
  - importlib_metadata
  - importlib_resources
  - importstring
  - in_memory
  - indent
  - initialise
  - inputhook
  - inputtransformer2
  - inspect
  - install
  - install_scripts
  - installer
  - interactiveshell
  - intranges
  - io
  - iostream
  - ipaddress
  - ipdoctest
  - ipkernel
  - ipunittest
  - ipykernel
  - ipyparallel
  - ipython_denied_module
  - ipywidgets
  - isoduration
  - isoparser
  - itertools
  - java
  - jedi
  - jinja2
  - jisfreq
  - jnius
  - johabfreq
  - johabprober
  - jpcntx
  - json
  - json_compat
  - jsonpointer
  - jsonschema
  - jsonschema_specifications
  - jsonutil
  - jupyter
  - jupyter_client
  - jupyter_core
  - keras
  - kernelapp
  - kernelbase
  - kernelspec
  - key_binding
  - key_bindings
  - key_processor
  - keyring
  - keys
  - keyword
  - labels
  - langbulgarianmodel
  - langgreekmodel
  - langhebrewmodel
  - langrussianmodel
  - langthaimodel
  - langturkishmodel
  - latin1prober
  - launcher
  - layout
  - lib
  - lib2to3
  - libdisassemble
  - line_numbers
  - linecache
  - live
  - live_render
  - lldb
  - loader
  - local_provisioner
  - locale
  - localinterfaces
  - locks
  - log
  - logging
  - lzma
  - macos
  - macosx_libfile
  - macro
  - macromanprober
  - magic
  - magics
  - main
  - manager
  - managerabc
  - managers
  - margins
  - mark_tokens
  - markers
  - markup
  - marshal
  - math
  - matplotlib
  - matplotlib_inline
  - mbcharsetprober
  - mbcsgroupprober
  - mbcssm
  - measure
  - menus
  - message
  - metadata
  - migrate
  - mimetypes
  - minitornado
  - mmap
  - mock
  - models
  - monkey
  - more
  - mouse_handlers
  - msvcrt
  - multikernelmanager
  - multiprocessing
  - my_getattr_static
  - named_colors
  - named_commands
  - namespace
  - nap
  - nbbase
  - nbformat
  - nbjson
  - nbpy
  - nbxml
  - nest_asyncio
  - nested
  - netifaces
  - netrc
  - nis
  - nose
  - notebook
  - notebooknode
  - nt
  - ntlm
  - ntpath
  - ntsecuritycon
  - nturl2path
  - numbers
  - numpy
  - numpydoc
  - opcode
  - operator
  - optparse
  - org
  - os
  - os_helper
  - osm
  - output
  - pack
  - package_data
  - packages
  - packaging
  - padding
  - pager
  - palette
  - pandas
  - panel
  - paramiko
  - parentpoller
  - parso
  - patcomp
  - pathlib
  - paths
  - pdb
  - pexpect
  - pgen2
  - pickle
  - pickleshare
  - pickletools
  - pip
  - pkg_resources
  - pkgutil
  - pkgutil_resolve_name
  - plain_text
  - platform
  - platformdirs
  - plistlib
  - poll
  - pool
  - poolmanager
  - popen_fork
  - popen_forkserver
  - popen_spawn_posix
  - popen_spawn_win32
  - posix
  - posix_pipe
  - posix_utils
  - posixpath
  - pprint
  - pretty
  - process
  - processors
  - profile
  - progress_bar
  - prompt
  - prompt_toolkit
  - prompts
  - protocol
  - protocols
  - providers
  - provisioner_base
  - provisioning
  - pstats
  - psutil
  - psyco
  - pt_inputhooks
  - ptutils
  - pty
  - pty_spawn
  - ptyprocess
  - pure_eval
  - pwd
  - py
  - py38
  - py38compat
  - py39compat
  - py_compile
  - pycares
  - pyclbr
  - pycurl
  - pyczmq
  - pydasm
  - pydev_ipython
  - pydev_pysrc
  - pydevconsole
  - pydevd
  - pydevd_base_schema
  - pydevd_file_utils
  - pydevd_helpers
  - pydevd_plugins
  - pydevd_tracing
  - pydoc
  - pydoc_data
  - pyexpat
  - pyglet
  - pygments
  - pygram
  - pylab
  - pylabtools
  - pyparsing
  - pyperclip
  - pyperf
  - pysqlite2
  - pytest
  - pytree
  - queue
  - queues
  - quopri
  - railroad
  - random
  - re
  - reader
  - readline
  - recipes
  - redis
  - ref_resolver
  - referencing
  - regex
  - regex_parser
  - region
  - reporters
  - repr
  - reprlib
  - req_file
  - req_install
  - req_set
  - request
  - requests
  - requirements
  - resolvers
  - resource
  - resource_sharer
  - resource_tracker
  - resources
  - response
  - restarter
  - result
  - resultdict
  - results
  - retry
  - rfc3339_validator
  - rfc3986_validator
  - rfc3987
  - rich
  - rlcompleter
  - rpds
  - rule
  - run
  - run_in_terminal
  - runner
  - runners
  - runpy
  - rwbase
  - sbcharsetprober
  - sbcsgroupprober
  - sched
  - scope
  - screen
  - script
  - scroll
  - scrollable_pane
  - search
  - secrets
  - segment
  - select
  - selection
  - selectors
  - sentinel
  - serialize
  - serializing
  - server
  - session
  - sessions
  - setup
  - setuptools
  - setuptools_scm
  - sharedctypes
  - shlex
  - shortcuts
  - shutil
  - signal
  - signals
  - sip
  - site
  - sitecustomize
  - six
  - sjisprober
  - slack
  - slack_sdk
  - smtplib
  - socket
  - socketserver
  - socks
  - sources
  - spawn
  - spawnbase
  - specifiers
  - sphinx
  - spinner
  - splitinput
  - sql
  - sqlalchemy
  - sqlite3
  - ssh
  - ssl
  - ssl_
  - ssltransport
  - stack_data
  - stackless
  - stat
  - statistics
  - status
  - status_codes
  - std
  - stop
  - streams
  - string
  - stringprep
  - struct
  - structs
  - structures
  - style
  - style_transformation
  - styled
  - subprocess
  - suite
  - synchronize
  - syntax
  - sys
  - sysconfig
  - syslog
  - system
  - table
  - table_vs16
  - table_wide
  - table_zero
  - tabnanny
  - tags
  - tarfile
  - taskgroups
  - tasks
  - telegram
  - tempfile
  - tensorflow
  - terminal
  - terminal_theme
  - termios
  - test
  - test_debugger
  - testing
  - testpath
  - tests_python
  - text
  - text_file
  - textio
  - textwrap
  - theme
  - thread
  - threading
  - threads
  - time
  - timeit
  - timeout
  - timeouts
  - tkinter
  - token
  - tokenize
  - tomllib
  - toolbars
  - tornado
  - tqdm
  - trace
  - traceback
  - tracemalloc
  - traitlets
  - transports
  - trio
  - trove_classifiers
  - tty
  - tunnel
  - turtle
  - turtledemo
  - twisted
  - types
  - typing
  - typing_extensions
  - tz
  - unicode
  - unicode_versions
  - unicodedata
  - unittest
  - universaldetector
  - unix
  - unix_events
  - unixccompiler
  - unpack
  - upload
  - uri_template
  - url
  - urllib
  - urllib2
  - urllib3_secure_extra
  - urlparse
  - usercustomize
  - utf1632prober
  - utf8prober
  - util
  - utils
  - utils_worker
  - uts46data
  - uuid
  - v4
  - validation
  - validator
  - vendored
  - version
  - vms_lib
  - vt100
  - vt100_parser
  - wait
  - warnings
  - wave
  - wcwidth
  - weakref
  - webbrowser
  - webcolors
  - wheel
  - wheelfile
  - win
  - win32
  - win32_pipe
  - win32api
  - win32clipboard
  - win32con
  - win32evtlog
  - win32evtlogutil
  - win32process
  - win32security
  - win_interrupt
  - winappdbg
  - windows
  - windows10
  - windows_events
  - winreg
  - winterm
  - wmi
  - word_completer
  - wsgiref
  - wx
  - x_user_defined
  - xml
  - xmlreader
  - xmlrpc
  - xmlrpclib
  - yapf
  - zipfile
  - zipimport
  - zipp
  - zlib
  - zmq
  - zmqshell
